version: 1.7.{build}
branches:
  only:
  - master
image: Visual Studio 2017
environment:
  my_signing_key:
    secure: 5+tJAGXhhYmF4qwybdyR9Au9ebFGsRzEXEPGCjsM8dFVhm85V5aqvInGtw9MIr9g4/F+neEH4yHwDIDSIiFNkmRJkOPaR1p2WxWVMNF4q1DlOWXUym72a8Dn5DUoE17x0J5zLVioM5Sdi5cJuNlC+lkYMNj9EU91QZEHp34HfUHXlxqKIoTM/XsnfqyDGTnRPuFATp2aHdDy47q7vjZRg1yqAxTRm3S1JIC9vkLgDdbUR0Q+e2ngPEuDZWqhqbnxRdXU3tgi8fyCcZxmOB+2uJvscBzD33xH0ZOqWcp0ucivECbPz0HLTS2gUIE+ekA6Dc/frZU7uAQ4/zDa/nz9edyG+E8kucZZBkUG66avUU24baiabI1L1JWqO0YtxE+MdxFKD8MQTu7j8cbJ+xI9Nc9AeEQsm4si4ZAVNvKJyEDlK2MVdlS+QguhYKmHIskPkdihnVQzz+U9XB+hk5UC8saWp57G0q/ixTn3QTdPKLxFJIMHaYDaoLrmUsPm6+GyUK05WdRl8KbM9p1T74RbvgJE7P2o7NRwTF72tTQadtm/9qXWW6bHCYhxkEIVlfldi2siqGDRUPoMsZH7cuPTKhx4z9HmE5l+H3bg++u6pcKWjWYFOh7LS69eMmsuK3xzks7WD2p9XlNsfHkg0zqYMCFcBB6NHRD9zHi5RZn086ew5LsShByQRwTuLuIBrykdGxZxCNb9us2SaZ9vFxHJRfKgOS9smBMDTLEIdOVl5kOManQwvukglxveJcOJciFc4EfuPvXIlfsDbtX9bmqKmNGXH9hS36Z9i/09x2T9ct0RXgWPiwxQlKDFa6190g8WxFhDJoiu46INF+MbaDQsYxff2CwkWeHcwqzrHHONG0iGu45/YsjIyOIFhKYHNRFQ0aOrBduXth8ZbkLO3SwDG7MLXtHIobk2MWdFjqT8bh1NX95ISsH+dNNHLxA9x24jqbWH5jBmFQTC7KvQFRSS+vy4VeLMah+YcZD/DheE66kZL7s3CWsBHo4P11R8ibQdGOv6B97Pejmj4OHyPivxbSyNvM4RUM0yh2nN7KpUsXs=
  my_variable:
    secure: Qpq/4cyuTUzmt/r4HsQxioG6WXrZSK3mzVq5iUJC2RI=
  NugetApiKey:
    secure: Ar6IQ+BxCwH6r8SgUB+6wzlWRD0Y+pkW+eFhZUTsF/yb5SyfEcDV7RNzzbGGe26Y
  ChocolateyApiKey:
    secure: klwi3/bn7RRe4vsqMat7GNNaD1kToVyewIAD5MPSptorqJZbySOF6wio/KW9SYza
  GitHubApiKey:
    secure: N83nQZ/QQVqpRnl0D6F/xSbKjn062y07JdskpUpbWryMY2JDo4Be9lUXmob+xcOO
build_script:
- cmd: PowerShell.exe -NoProfile -ExecutionPolicy Bypass -Command "& '.\build.ps1' --target Clean Publish ChangeVersionNumber --Configuration Release"
test: off
artifacts:
- path: bin\Release\
  name: Release-files
- path: bin\**\*.zip
- path: bin\**\*.nupkg
