version: 0.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore src/LogExpert.sln
build:
  project: src/LogExpert.sln
  parallel: true
  verbosity: minimal
test: off
artifacts:
- path: bin\Release\
  name: ci-Development